name: SonarQube analysis
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  scan:
    uses: "delphai/.github/.github/worklows/callable-sonarqube.yml@master"
    secrets: inherit
